name: Automated checks

permissions:
  # Read is required for actions/checkout / Write is required for publishing test report artifact to Github Pages
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  buffalo-cli-version: '0.18.13'
  #PostgreSQL Credentials
  PGUSER: paphos
  PGPASSWORD: paphos

jobs:
  paphos-backend-tests:
    runs-on: ubuntu-latest

    # PostgreSQL as Service Container - Directly on the Runner without a Container, since a container seems to cause issues with buffalo install
    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{  env.PGUSER  }}
          POSTGRES_PASSWORD: ${{  env.PGPASSWORD  }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true

      - name: Get cached Buffalo installation
        # cache is automatically saved after this job completes
        id: buffalo-cache-step
        uses: actions/cache@v3
        with:
          path: '/usr/local/bin/buffalo'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/config/buffalo-plugins.toml') }}

      - name: Install Buffalo
        if: steps.buffalo-cache-step.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/gobuffalo/cli/releases/download/v0.18.13/buffalo_${{  env.buffalo-cli-version  }}_Linux_x86_64.tar.gz
          tar -xvzf buffalo_${{  env.buffalo-cli-version  }}_Linux_x86_64.tar.gz
          sudo mv buffalo /usr/local/bin/buffalo

      - name: Get cached dependencies
        # cache is automatically saved after this job completes
        id: buffalo-cache-dependencies-step
        uses: actions/cache@v3
        with:
          # buffalo-pop plugin in /go/bin/ folder
          path: '/home/runner/go/bin'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/config/buffalo-plugins.toml') }}

      - name: Install Buffalo plugins
        if: steps.buffalo-cache-dependencies-step.outputs.cache-hit != 'true'
        run: buffalo plugins install

      - name: Create test database
        run: buffalo pop create -a

      - name: Apply migrations on the test database
        run: buffalo pop migrate

      - name: Build the project
        run: buffalo build

      - name: Run tests and collect coverage data
        run: buffalo test -coverprofile=c.out ./...

      - name: Generate coverage report
        if: success() || failure() # Always run, including if earlier steps failed
        run: go tool cover -html c.out -o coverage_report.html

      - name: Upload coverage report artifact
        if: success() || failure() # Always run, including if earlier steps failed
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: ./coverage_report.html
